FHIR-MIS-web/ViewModels/SearchViewModel.cs
using FHIR_MIS_web.Data.Enums;
using FHIR_MIS_web.Interfaces;
using Hl7.Fhir.Model;
using Hl7.Fhir.Rest;
using Hl7.Fhir.Utility;
using System.Text;

namespace FHIR_MIS_web.ViewModels
{
    public class SearchViewModel : ISearchString
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FathersName { get; set; }
        public GenderEnum Gender { get; set; }
        public DateTime Birthday { get; set; }

        public string[] FormSearchStrings()
        {
            List<string> forms = new List<string>();
            if (!string.IsNullOrEmpty(LastName))
            {
                forms.Add($"family:exact={LastName}");
            }
            if (!string.IsNullOrEmpty($"given:exact={FirstName}"))
            {
                forms.Add(FirstName);
            }
            if (!string.IsNullOrEmpty(FathersName))
            {
                forms.Add(FathersName);
            }
            if (Gender != null) { }
            {
                forms.Add($"gender={Gender}");
            }
            if(Birthday!= null)
            {
                forms.Add($"birthdate={Birthday.Year}.{Birthday.Month}.{Birthday.Day}");
            }
            return forms.ToArray();
        }

        public SearchParams SeacrhParam()
        {
            var searchParams = new SearchParams();

            if (!string.IsNullOrEmpty(LastName))
            {
                searchParams.Where($"family:exact={LastName}");
            }
            if (!string.IsNullOrEmpty(FirstName))
            {
                searchParams.Where($"given:exact={FirstName}");
            }
            //searchParams.Where($"gender={Gender}");
            return searchParams;
                //new SearchParams()
                //.Where($"family:exact={LastName}")
                //.Where($"given:exact={FirstName} {FathersName}")
                //.Where($"gender={Gender}");
               
        }
    }
}

FHIR-MIS-web/Controllers/FireLyController.cs
using Microsoft.AspNetCore.Mvc;
using Hl7.Fhir.Model;
using Hl7.Fhir.Rest;
using System.ComponentModel.DataAnnotations;
using FHIR_MIS_web.ViewModels;
using FHIR_MIS_web.Interfaces;
using Serilog;
using FHIR_MIS_web.Data;
using FHIR_MIS_web.FHIR;
using System.IO;
using Microsoft.Extensions.Options;

namespace FHIR_MIS_web.Controllers
{
    public class FireLyController : Controller
    {
        FhirClient fhirClient;
        public FireLyController(IOptions<FhirServerSettings> server)
        {
            fhirClient = new FhirClient(server.Value.Url);
        }
        
        public async Task<IActionResult> Index()
        {
            PatientPull.Pull.Clear();
            IEnumerable<FireLyPatientViewModel> toView = ViewModelMapper.
                PatientToFireLyVM(
                await PatientWrapper.GetPatients(fhirClient)
                );
            return View(toView);
        }

        public async Task<IActionResult> SearchResult(SearchViewModel searchViewModel)
        {
            IEnumerable<FireLyPatientViewModel> toView = ViewModelMapper
                .PatientToFireLyVM(
                await PatientWrapper.GetPatients(fhirClient)
                );
            return View(toView);
        }

        public IActionResult Search()
        {
            return View();
        }

    }
}

FHIR-MIS-web/Controllers/PatientController.cs
using FHIR_MIS_web.Interfaces;
using FHIR_MIS_web.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Hl7.Fhir.Model;
using System.Globalization;
using FHIR_MIS_web.Data;

namespace FHIR_MIS_web.Controllers
{
    public class PatientController : Controller
    {
        IServerPatientRepository _serverPatientRepository;
        public PatientController(IServerPatientRepository serverPatientRepository)
        {
            _serverPatientRepository = serverPatientRepository;
        }
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreatePatientViewModel viewModel)
        {
            IEnumerable<string> GivenName = new List<string>()
            {
                viewModel.Name,
                viewModel.Patronymic
            };
            _serverPatientRepository.Create(new Patient()
            {
                //Имя
                Name = new List<HumanName>()
                {
                    new HumanName()
                    {
                        Family = viewModel.Surname,
                        Given = GivenName,
                    }
                },
                Gender = viewModel.FhirGender,
                BirthDate = viewModel.BirthDate.ToString("yyyy-MM-dd"),
                Telecom = new List<ContactPoint> { new ContactPoint()
                {
                    System = ContactPoint.ContactPointSystem.Phone,
                    Value = viewModel.Telephone
                } }
            });
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Detail(string id)
        {
            Patient patient = _serverPatientRepository.GetById(id);
            bool hasGivenName = patient.Name.FirstOrDefault().Given.Count() > 0;
            PatientPull.Pull.Add(id, patient);
            var vm = new DetailPatientViewModel()
            {
                PatientId = id,
                Name = hasGivenName ? patient.Name.FirstOrDefault().GivenElement.FirstOrDefault().Value : "",
                Surname = patient.Name.FirstOrDefault().Family,
                Patronymic = hasGivenName ? patient.Name.FirstOrDefault().GivenElement.LastOrDefault().Value : "",
                Adress = patient.Address.FirstOrDefault(),
                Birthdate = patient.BirthDate,
                Gender = patient.Gender.HasValue ? patient.Gender : AdministrativeGender.Unknown,
            };
            return View(vm);

        }

        public async Task<IActionResult> Delete(string id)
        {
            return _serverPatientRepository.Delete(id) ? RedirectToAction("Index") : RedirectToAction("Index");
        }

        [HttpGet]
        public async Task<IActionResult> Update(string id)
        {
            Patient patient = PatientPull.Pull[id];
            bool hasGivenName = patient.Name.FirstOrDefault().Given.Count() > 0;
            bool hasAddress = patient.Address.Count > 0;
            UpdatePatientViewModel vm = new UpdatePatientViewModel()
            {
                PatientId = id,
                Name = hasGivenName ? patient.Name.FirstOrDefault().GivenElement.FirstOrDefault().Value : "",
                Surname = patient.Name.FirstOrDefault().Family,
                Patronymic = hasGivenName ? patient.Name.FirstOrDefault().GivenElement.FirstOrDefault().Value : "",
                City = hasAddress ? patient.Address.FirstOrDefault().City : "",
                Street = hasAddress ? patient.Address.FirstOrDefault().Line.FirstOrDefault() : "",
                BirthDate = patient.BirthDate,
                Gender = patient.Gender.HasValue ? patient.Gender : AdministrativeGender.Unknown,
            };
            return View(vm);
        }
        [HttpPost]
        public async Task<IActionResult> Update(UpdatePatientViewModel viewModel)
        {
            Patient pat = PatientPull.Pull[viewModel.PatientId];
            HumanName name = new HumanName
            {
                Family = viewModel.Surname,
                Given = new string[]
                {
                    viewModel.Name,
                    viewModel.Patronymic
                }
            };
            ContactPoint telephone = new ContactPoint()
            {
                Value = viewModel.Telephone,
                System = ContactPoint.ContactPointSystem.Phone

            };
            Address address = new Address()
            {
                City = viewModel.City,
                Line = new string[]
                {
                    viewModel.Street
                }
            };
            pat.Name.Clear();
            pat.Name.Add(name);
            pat.BirthDate = viewModel.BirthDate;
            pat.Gender = viewModel.Gender;
            pat.Telecom.Clear();
            pat.Telecom.Add(telephone);
            pat.Address.Clear();
            pat.Address.Add(address);

            PatientPull.Pull.Clear();
            return _serverPatientRepository.Update(pat) ? RedirectToAction("Detail", new { id = viewModel.PatientId }) : RedirectToAction("Index","FireLy");
        }
    }
}

FHIR-MIS-web/Views/FireLy/Index.cshtml
@using Hl7.Fhir.Model;
@using FHIR_MIS_web.ViewModels;

@model IEnumerable<FireLyPatientViewModel>;

@{
    FireLyPatientViewModel Search = new FireLyPatientViewModel();
}

<link rel="stylesheet" href="~/css/style.css"/>
 
<div class="row">
    <div class="col-md-8">
        <table class="table table-bordered table-hover">
            <tr>
                <th>Id</th>
                <th>ФИО</th>
                <th>Пол</th>
                <th>Дата рождения</th>
                <th>Адресс</th>
            </tr>  
            @foreach (var item in @Model)
            {
                 <tr>
                     <td>@item.Id</td>
                    <td>@item.FullName()</td>
                    <td>@item.Gender</td>
                    <td>@item.Birthday</td>
                    <td>@item.FullAddress()</td>
                    <td>
                        <a class="btn btn-primary" asp-controller="Patient" asp-action="Detail" asp-route-id="@item.Id"></a>
                    </td>
                 </tr>
            }
        </table>
    </div>
    <div class="col-md-4"> 
            <div>
                <a asp-action="Search" class="btn btn-primary">Поиск</a>
                <a asp-controller="Patient" asp-action="Create" class="btn btn-primary">Создать</a>
            </div>
    </div>
</div>

FHIR-MIS-web/Views/FireLy/Search.cshtml
@using FHIR_MIS_web.ViewModels
@using FHIR_MIS_web.Data.Enums
@model SearchViewModel;

<form asp-action="SearchResult" asp-controller="FireLy" enctype="multipart/form-data" method="post">
    <div class="col-md-4">
        <h4 class="card-title">Поиск</h4>
        <div>
            <label asp-for="LastName">Фамилия</label>
            <input asp-for=LastName class="form-control"/>
            <label asp-for="FirstName">Имя</label>
            <input asp-for=FirstName class="form-control"/>
            <label asp-for="FathersName">Отчество</label>
            <input asp-for=FathersName class="form-control"/>
            <div class="row">
                <div class="col-md-2">
                    <label asp-for="Gender">Пол</label>
                    <select asp-for=Gender asp-items="@Html.GetEnumSelectList<GenderEnum>()" class="form-select-sm">
                        <option selected="selected" value=""></option>
                    </select>
                </div>
                <div class="col-md-4 offset-4">
                    <label asp-for="Birthday">Дата рождения</label>
                    <input asp-for=Birthday type="date" class="form-control"/>
                </div>
            </div>
            <div>
                <p>Адрес</p>
                <input class="form-control"/>
            </div>

        </div>
        <input type="submit" class="btn btn-primary"/>
    </div>
</form>

FHIR-MIS-web/Views/FireLy/SearchResult.cshtml
@using FHIR_MIS_web.ViewModels
@model IEnumerable<FireLyPatientViewModel>;



<div class="row">
    <div class="col-md-8">
        <table class="table table-bordered table-hover">
            <tr>
                <th>Id</th>
                <th>ФИО</th>
                <th>Пол</th>
                <th>Дата рождения</th>
                <th>Адресс</th>
            </tr>
            @foreach (var item in @Model)
            {
                <tr>
                    <td>@item.Id</td>
                    <td>@item.FullName()</td>
                    <td>@item.Gender</td>
                    <td>@item.Birthday</td>
                    <td>@item.FullAddress()</td>
                </tr>
            }
        </table>
    </div>
    <div>
        <div>
            <a asp-action="Search" class="btn btn-primary">Поиск</a>
        </div>
    </div>
</div>